name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  docker:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate Date-Based Tag
      id: date_tag
      run: echo "DATE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Generate Build Number Tag
      id: build_tag
      run: echo "BUILD_TAG=build-${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: | 
          mustaman/cloudai-parser:latest 
          mustaman/cloudai-parser:${{ env.DATE_TAG }}
          mustaman/cloudai-parser:${{ env.BUILD_TAG }}
          mustaman/cloudai-parser:${{ github.sha }}